hubert_config:
  # hubertsoft:     xxx.pt      hid_dim: 256
  # cnhubert:       xxx_folder  hid_dim: 768    推荐
  # cnhubert-large: xxx_folder  hid_dim: 1024
  # whisper-ppg:    xxx.pt      hid_dim: 1024
  encoder: cnhubert
  model_path: dependencies/cnhubert
  sample_rate: 16000
  hop_size: 320
  channel: 768

hnspe_config:
  hnspe_model_path: dependencies/vr/model.pt
  use_hnspe_aug: False

pre_emphasis_config:
  use_pre_emphasis_aug: False

# 只检测data文件夹下，"full_label"、"weak_label"、"no_label"、"evaluate"文件夹内数据
# evaluate路径固定为{datafolder}/evaluate，格式同full_label。可留空，此时evaluate_loss不生效
data_folder: data/
binary_folder: data/binary_base

valid_set_size: 15

# valid_sets: [] 时，按valid_set_size数量随机抽取
valid_sets: []
valid_set_preferred_folders:
  - test
ignored_phonemes:
  - AP
  - SP
  - EP
  - GS
  - <AP>
  - <SP>
  - ''
  - pau
  - cl

# Mandatory marking as vowel
vowel_phonemes:
  - y
  - w

# Two-part dictionary used to determine vowels
dictionary_paths:
  - dictionary/opencpop-extension.txt
max_length: 45 # unit: second


melspec_config:
  n_mels: 128
  sample_rate: 44100
  win_length: 1024
  hop_length: 512
  n_fft: 2048
  fmin: 40
  fmax: 16000
  clamp: 0.00001

# 不建议开启
merged_phoneme: False
merged_phoneme_groups:
  - [ b,p ]
  - [ d,t ]
  - [ g,k ]
  - [ z,c,s ]
  - [ zh,ch,sh,r ]
  - [ j,q,x ]

  - [ a,ia,ua ]
  - [ ai,uai ]
  - [ ao,iao ]
  - [ an,ian,van,En ]
  - [ ang,iang,uang ]
  - [ en,in,vn ]
  - [ eng,ing ]
  - [ ong,iong ]
  - [ ou,iu ]
  - [ ie,ve ]